// auth.js
export const LOGOUT = 'LOGOUT';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const UPDATE_USER = 'UPDATE_USER';

// primary drawer
export const REPLACE_PRIMARY_DRAWER = 'REPLACE_PRIMARY_DRAWER';

// type users
export const REPLACE_LOADING_TYPE_USERS = 'REPLACE_LOADING_TYPE_USERS';
export const REPLACE_TYPE_USERS = 'REPLACE_TYPE_USERS';

// users
export const REPLACE_SHOW_MODAL_LOGIN = 'REPLACE_SHOW_MODAL_LOGIN';
export const REPLACE_LOADING_USERS = 'REPLACE_LOADING_USERS';
export const REPLACE_USERS = 'REPLACE_USERS';
export const REPLACE_SHOW_MODAL_DELETE_USER = 'REPLACE_SHOW_MODAL_DELETE_USER';
export const REPLACE_CURRENT_USER = 'REPLACE_CURRENT_USER';
export const REPLACE_LOADING_CURRENT_USER = 'REPLACE_LOADING_CURRENT_USER';

// courses
export const REPLACE_LOADING_COURSES = 'REPLACE_LOADING_COURSES';
export const REPLACE_COURSES = 'REPLACE_COURSES';
export const REPLACE_SHOW_MODAL_DELETE_COURSE = 'REPLACE_SHOW_MODAL_DELETE_COURSE';
export const REPLACE_CURRENT_COURSE = 'REPLACE_CURRENT_COURSE';
export const REPLACE_LOADING_CURRENT_COURSE = 'REPLACE_LOADING_CURRENT_COURSE';
export const REPLACE_LOADING_TIPO_CURSOS  = 'REPLACE_LOADING_TIPO_CURSOS';
export const REPLACE_TIPO_CURSOS  = 'REPLACE_TIPO_CURSOS';
export const REPLACE_LOADING_COLABORADORES_DISPONIBLES = 'REPLACE_LOADING_COLABORADORES_DISPONIBLES';
export const REPLACE_COLABORADORES_DISPONIBLES = 'REPLACE_COLABORADORES_DISPONIBLES';
export const REPLACE_LOADING_CURSOS_DISPONIBLES = 'REPLACE_LOADING_CURSOS_DISPONIBLES';
export const REPLACE_CURSOS_DISPONIBLES = 'REPLACE_CURSOS_DISPONIBLES';

// niveles jerarquico
export const REPLACE_LOADING_NIVELES_JERARQUICO = 'REPLACE_LOADING_NIVELES_JERARQUICO';
export const REPLACE_NIVELES_JERARQUICO = 'REPLACE_NIVELES_JERARQUICO';
export const REPLACE_SHOW_MODAL_DELETE_NIVEL_JERARQUICO = 'REPLACE_SHOW_MODAL_DELETE_NIVEL_JERARQUICO';
export const REPLACE_CURRENT_NIVEL_JERARQUICO = 'REPLACE_CURRENT_NIVEL_JERARQUICO';
export const REPLACE_LOADING_CURRENT_NIVEL_JERARQUICO = 'REPLACE_LOADING_CURRENT_NIVEL_JERARQUICO';

// estado civiles
export const REPLACE_LOADING_ESTADO_CIVILES = 'REPLACE_LOADING_ESTADO_CIVILES';
export const REPLACE_ESTADO_CIVILES = 'REPLACE_ESTADO_CIVILES';

// niveles educacion
export const REPLACE_LOADING_NIVELES_EDUCACION = 'REPLACE_LOADING_NIVELES_EDUCACION';
export const REPLACE_NIVELES_EDUCACION = 'REPLACE_NIVELES_EDUCACION';

// tags
export const REPLACE_LOADING_TAGS = 'REPLACE_LOADING_TAGS';
export const REPLACE_TAGS = 'REPLACE_TAGS';
export const REPLACE_SHOW_MODAL_DELETE_TAG = 'REPLACE_SHOW_MODAL_DELETE_TAG';
export const REPLACE_CURRENT_TAG = 'REPLACE_CURRENT_TAG';
export const REPLACE_LOADING_CURRENT_TAG = 'REPLACE_LOADING_CURRENT_TAG';

// colaboradores
export const REPLACE_LOADING_COLABORADORES = 'REPLACE_LOADING_COLABORADORES';
export const REPLACE_COLABORADORES = 'REPLACE_COLABORADORES';
export const REPLACE_LOADING_CARGA_FAMILIAR = 'REPLACE_LOADING_CARGA_FAMILIAR';
export const REPLACE_CARGA_FAMILIAR = 'REPLACE_CARGA_FAMILIAR';
export const REPLACE_LOADING_TIPOS_CARGA = 'REPLACE_LOADING_TIPOS_CARGA';
export const REPLACE_TIPOS_CARGA = 'REPLACE_TIPOS_CARGA';
export const REPLACE_CURRENT_COLABORADOR = 'REPLACE_CURRENT_COLABORADOR';
export const REPLACE_CURRENT_FAMILY = 'REPLACE_CURRENT_FAMILY';
export const REPLACE_LOADING_COLABORADOR_CURSOS = 'REPLACE_LOADING_COLABORADOR_CURSOS';
export const REPLACE_COLABORADOR_CURSOS = 'REPLACE_COLABORADOR_CURSOS';
export const REPLACE_CURRENT_CURSO = 'REPLACE_CURRENT_CURSO';
export const REPLACE_SHOW_MODAL_DELETE_CURSO = 'REPLACE_SHOW_MODAL_DELETE_CURSO';
export const REPLACE_CURRENT_CAPACITACION = 'REPLACE_CURRENT_CAPACITACION';
// areas
export const REPLACE_LOADING_AREAS = 'REPLACE_LOADING_AREAS';
export const REPLACE_AREAS = 'REPLACE_AREAS';
export const REPLACE_SHOW_MODAL_DELETE_AREA = 'REPLACE_SHOW_MODAL_DELETE_AREA';
export const REPLACE_CURRENT_AREA = 'REPLACE_CURRENT_AREA';
export const REPLACE_LOADING_CURRENT_AREA = 'REPLACE_LOADING_CURRENT_AREA';
export const REPLACE_CURRENT_AREAS_RELACIONADOS = 'REPLACE_CURRENT_AREAS_RELACIONADOS';

// tipos Area
export const REPLACE_LOADING_TIPOS_AREA = 'REPLACE_LOADING_TIPOS_AREA';
export const REPLACE_TIPOS_AREA = 'REPLACE_TIPOS_AREA';
export const REPLACE_SHOW_MODAL_DELETE_TIPO_AREA = 'REPLACE_SHOW_MODAL_DELETE_TIPO_AREA';
export const REPLACE_CURRENT_TIPO_AREA = 'REPLACE_CURRENT_TIPO_AREA';
export const REPLACE_LOADING_CURRENT_TIPO_AREA = 'REPLACE_LOADING_CURRENT_TIPO_AREA';

// cargos
export const REPLACE_LOADING_CARGOS = 'REPLACE_LOADING_CARGOS';
export const REPLACE_CARGOS = 'REPLACE_CARGOS';
export const REPLACE_SHOW_MODAL_DELETE_CARGO = 'REPLACE_SHOW_MODAL_DELETE_CARGO';
export const REPLACE_CURRENT_CARGO = 'REPLACE_CURRENT_CARGO';
export const REPLACE_LOADING_CURRENT_CARGO = 'REPLACE_LOADING_CURRENT_CARGO';
export const REPLACE_CURRENT_CARGOS_AREAS_RELACIONADOS = 'REPLACE_CURRENT_CARGOS_AREAS_RELACIONADOS';

// movilidades
export const REPLACE_LOADING_MOVILIDADES = 'REPLACE_LOADING_MOVILIDADES';
export const REPLACE_MOVILIDADES = 'REPLACE_MOVILIDADES';
export const REPLACE_LOADING_TIPO_MOVILIDADES = 'REPLACE_LOADING_TIPO_MOVILIDADES';
export const REPLACE_TIPO_MOVILIDADES = 'REPLACE_TIPO_MOVILIDADES';
export const REPLACE_CURRENT_MOVILIDAD = 'REPLACE_CURRENT_MOVILIDAD';
export const REPLACE_SHOW_MODAL_DELETE_MOVILIDAD = 'REPLACE_SHOW_MODAL_DELETE_MOVILIDAD';
export const REPLACE_LOADING_CURRENT_MOVILIDAD = 'REPLACE_LOADING_CURRENT_MOVILIDAD';

// administradores

export const REPLACE_LOADING_ADMINISTRADORES = 'REPLACE_LOADING_ADMINISTRADORES';
export const REPLACE_ADMINISTRADORES = 'REPLACE_ADMINISTRADORES';
export const REPLACE_CURRENT_ADMINISTRADOR = 'REPLACE_CURRENT_ADMINISTRADOR';

// comentarios
export const REPLACE_LOADING_COMENTARIOS = 'REPLACE_LOADING_COMENTARIOS';
export const REPLACE_COMENTARIOS = 'REPLACE_COMENTARIOS';
export const REPLACE_SHOW_MODAL_DELETE_COMENTARIO = 'REPLACE_SHOW_MODAL_DELETE_COMENTARIOS';
export const REPLACE_CURRENT_COMENTARIO = 'REPLACE_CURRENT_COMENTARIOS';
export const REPLACE_LOADING_TIPO_COMENTARIOS = 'REPLACE_LOADING_TIPO_COMENTARIOS';
export const REPLACE_TIPO_COMENTARIOS = 'REPLACE_TIPO_COMENTARIOS';

// notificaciones
export const REPLACE_LOADING_NOTIFICACIONES = 'REPLACE_LOADING_NOTIFICACIONES';
export const REPLACE_NOTIFICACIONES = 'REPLACE_NOTIFICACIONES';

// consultas
export const REPLACE_LOADING_CONSULTAS = 'REPLACE_LOADING_CONSULTAS';
export const REPLACE_CONSULTAS = 'REPLACE_CONSULTAS';
export const REPLACE_SHOW_MODAL_VER_CONSULTAS = 'REPLACE_SHOW_MODAL_VER_CONSULTAS';
export const REPLACE_CURRENT_CONSULTA = 'REPLACE_CURRENT_CONSULTA';
