// auth.js
export const LOGOUT = 'LOGOUT';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const UPDATE_USER = 'UPDATE_USER';

// primary drawer
export const REPLACE_PRIMARY_DRAWER = 'REPLACE_PRIMARY_DRAWER';

// type users
export const REPLACE_LOADING_TYPE_USERS = 'REPLACE_LOADING_TYPE_USERS';
export const REPLACE_TYPE_USERS = 'REPLACE_TYPE_USERS';

// users
export const REPLACE_SHOW_MODAL_LOGIN = 'REPLACE_SHOW_MODAL_LOGIN';
export const REPLACE_LOADING_USERS = 'REPLACE_LOADING_USERS';
export const REPLACE_USERS = 'REPLACE_USERS';
export const REPLACE_SHOW_MODAL_DELETE_USER = 'REPLACE_SHOW_MODAL_DELETE_USER';
export const REPLACE_CURRENT_USER = 'REPLACE_CURRENT_USER';
export const REPLACE_LOADING_CURRENT_USER = 'REPLACE_LOADING_CURRENT_USER';

// courses
export const REPLACE_LOADING_COURSES = 'REPLACE_LOADING_COURSES';
export const REPLACE_COURSES = 'REPLACE_COURSES';
export const REPLACE_SHOW_MODAL_DELETE_COURSE = 'REPLACE_SHOW_MODAL_DELETE_COURSE';
export const REPLACE_CURRENT_COURSE = 'REPLACE_CURRENT_COURSE';
export const REPLACE_LOADING_CURRENT_COURSE = 'REPLACE_LOADING_CURRENT_COURSE';

// niveles jerarquico
export const REPLACE_LOADING_NIVELES_JERARQUICO = 'REPLACE_LOADING_NIVELES_JERARQUICO';
export const REPLACE_NIVELES_JERARQUICO = 'REPLACE_NIVELES_JERARQUICO';
export const REPLACE_SHOW_MODAL_DELETE_NIVEL_JERARQUICO = 'REPLACE_SHOW_MODAL_DELETE_NIVEL_JERARQUICO';
export const REPLACE_CURRENT_NIVEL_JERARQUICO = 'REPLACE_CURRENT_NIVEL_JERARQUICO';
export const REPLACE_LOADING_CURRENT_NIVEL_JERARQUICO = 'REPLACE_LOADING_CURRENT_NIVEL_JERARQUICO';

// estado civiles
export const REPLACE_LOADING_ESTADO_CIVILES = 'REPLACE_LOADING_ESTADO_CIVILES';
export const REPLACE_ESTADO_CIVILES = 'REPLACE_ESTADO_CIVILES';

// niveles educacion
export const REPLACE_LOADING_NIVELES_EDUCACION = 'REPLACE_LOADING_NIVELES_EDUCACION';
export const REPLACE_NIVELES_EDUCACION = 'REPLACE_NIVELES_EDUCACION';

// tags
export const REPLACE_LOADING_TAGS = 'REPLACE_LOADING_TAGS';
export const REPLACE_TAGS = 'REPLACE_TAGS';
export const REPLACE_SHOW_MODAL_DELETE_TAG = 'REPLACE_SHOW_MODAL_DELETE_TAG';
export const REPLACE_CURRENT_TAG = 'REPLACE_CURRENT_TAG';
export const REPLACE_LOADING_CURRENT_TAG = 'REPLACE_LOADING_CURRENT_TAG';

// colaboradores
export const REPLACE_LOADING_COLABORADORES = 'REPLACE_LOADING_COLABORADORES';
export const REPLACE_COLABORADORES = 'REPLACE_COLABORADORES';
export const REPLACE_LOADING_TIPOS_CARGA = 'REPLACE_LOADING_TIPOS_CARGA';
export const REPLACE_TIPOS_CARGA = 'REPLACE_TIPOS_CARGA';

// areas
export const REPLACE_LOADING_AREAS = 'REPLACE_LOADING_AREAS';
export const REPLACE_AREAS = 'REPLACE_AREAS';
export const REPLACE_SHOW_MODAL_DELETE_AREA = 'REPLACE_SHOW_MODAL_DELETE_AREA';
export const REPLACE_CURRENT_AREA = 'REPLACE_CURRENT_AREA';
export const REPLACE_LOADING_CURRENT_AREA = 'REPLACE_LOADING_CURRENT_AREA';

// tipos Area
export const REPLACE_LOADING_TIPOS_AREA = 'REPLACE_LOADING_TIPOS_AREA';
export const REPLACE_TIPOS_AREA = 'REPLACE_TIPOS_AREA';
export const REPLACE_SHOW_MODAL_DELETE_TIPO_AREA = 'REPLACE_SHOW_MODAL_DELETE_TIPO_AREA';
export const REPLACE_CURRENT_TIPO_AREA = 'REPLACE_CURRENT_TIPO_AREA';
export const REPLACE_LOADING_CURRENT_TIPO_AREA = 'REPLACE_LOADING_CURRENT_TIPO_AREA';
