// auth.js
export const LOGOUT = 'LOGOUT';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const UPDATE_USER = 'UPDATE_USER';

// primary drawer
export const REPLACE_PRIMARY_DRAWER = 'REPLACE_PRIMARY_DRAWER';

// type users
export const REPLACE_LOADING_TYPE_USERS = 'REPLACE_LOADING_TYPE_USERS';
export const REPLACE_TYPE_USERS = 'REPLACE_TYPE_USERS';

// users
export const REPLACE_SHOW_MODAL_LOGIN = 'REPLACE_SHOW_MODAL_LOGIN';
export const REPLACE_LOADING_USERS = 'REPLACE_LOADING_USERS';
export const REPLACE_USERS = 'REPLACE_USERS';
export const REPLACE_SHOW_MODAL_DELETE_USER = 'REPLACE_SHOW_MODAL_DELETE_USER';
export const REPLACE_CURRENT_USER = 'REPLACE_CURRENT_USER';
export const REPLACE_LOADING_CURRENT_USER = 'REPLACE_LOADING_CURRENT_USER';

// courses
export const REPLACE_LOADING_COURSES = 'REPLACE_LOADING_COURSES';
export const REPLACE_COURSES = 'REPLACE_COURSES';
export const REPLACE_SHOW_MODAL_DELETE_COURSE = 'REPLACE_SHOW_MODAL_DELETE_COURSE';
export const REPLACE_CURRENT_COURSE = 'REPLACE_CURRENT_COURSE';
export const REPLACE_LOADING_CURRENT_COURSE = 'REPLACE_LOADING_CURRENT_COURSE';

